/*Q1 What is the total revenue generated by male vs. female customers?*/
SELECT Gender, 
       SUM(`Purchase Amount (USD)`) AS revenue
FROM customers
GROUP BY Gender;

/* Q2 Which customers used a discount but still spent more than the average purchase amount? */
USE customer_behavior;

SELECT `Customer ID`, `Purchase Amount (USD)`
FROM customers
WHERE `Subscription Status` = 'Yes'
AND `Purchase Amount (USD)` >= (
    SELECT AVG(`Purchase Amount (USD)`)
    FROM customers
);

/*Q3 Top 5 products with highest average review rating*/
SELECT `Item Purchased`,
       ROUND(AVG(`Review Rating`), 2) AS average_product_rating
FROM customers
GROUP BY `Item Purchased`
ORDER BY average_product_rating DESC
LIMIT 5;

/* Q4 Compare avg purchase between Standard & Express*/
SELECT `Shipping Type`,
       ROUND(AVG(`Purchase Amount (USD)`), 2) AS avg_purchase
FROM customers
WHERE `Shipping Type` IN ('Standard', 'Express')
GROUP BY `Shipping Type`;

/* Q5 Do subscribed customers spend more?*/
SELECT `Subscription Status`,
       COUNT(`Customer ID`) AS total_customers,
       ROUND(AVG(`Purchase Amount (USD)`), 2) AS avg_spend,
       ROUND(SUM(`Purchase Amount (USD)`), 2) AS total_revenue
FROM customers
GROUP BY `Subscription Status`
ORDER BY total_revenue DESC;

/* Q6 Which 5 products generate the highest total revenue?*/
SELECT `Item Purchased`,
       SUM(`Purchase Amount (USD)`) AS total_revenue
FROM customers
GROUP BY `Item Purchased`
ORDER BY total_revenue DESC
LIMIT 5;

/* Q7 Segment customers by spending behavior*/
WITH customer_spending AS (
    SELECT `Customer ID`,
           SUM(`Purchase Amount (USD)`) AS total_spent
    FROM customers
    GROUP BY `Customer ID`
)

SELECT 
    CASE 
        WHEN total_spent < 200 THEN 'Low Spender'
        WHEN total_spent BETWEEN 200 AND 500 THEN 'Medium Spender'
        ELSE 'High Spender'
    END AS customer_segment,
    COUNT(*) AS number_of_customers
FROM customer_spending
GROUP BY customer_segment;

/* Q8 Top 3 products within each category*/
WITH item_counts AS (
    SELECT `Category`,
           `Item Purchased`,
           COUNT(*) AS total_orders,
           ROW_NUMBER() OVER (
               PARTITION BY `Category`
               ORDER BY COUNT(*) DESC
           ) AS item_rank
    FROM customers
    GROUP BY `Category`, `Item Purchased`
)

SELECT item_rank, `Category`, `Item Purchased`, total_orders
FROM item_counts
WHERE item_rank <= 3;

/* Q9 Are subscribers spending more?*/
SELECT `Subscription Status`,
       COUNT(`Customer ID`) AS total_customers,
       ROUND(AVG(`Purchase Amount (USD)`),2) AS avg_spend,
       SUM(`Purchase Amount (USD)`) AS total_revenue
FROM customers
GROUP BY `Subscription Status`;

/* Q10 Revenue contribution by age group*/
SELECT 
    CASE 
        WHEN Age < 20 THEN 'Teen'
        WHEN Age BETWEEN 20 AND 35 THEN 'Young Adult'
        WHEN Age BETWEEN 36 AND 55 THEN 'Adult'
        ELSE 'Senior'
    END AS age_group,
    SUM(`Purchase Amount (USD)`) AS total_revenue
FROM customers
GROUP BY age_group
ORDER BY total_revenue DESC;